project:
  type: website
  output-dir: docs

website:
  title: |
    ![](resources/2025logo.png){fig-alt="Posit" width=50px}
  description: ""
  site-url: https://github.com/pharmarug/pharmarug-2025
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: "house-fill"
      - href: program.qmd
        text: Program
        icon: "folder"
      - href: questions.qmd
        text: Q & A
        icon: "question-circleg"
      - href: highlights.qmd
        text: Event highlights
        icon: "camera"
  page-footer:
    left: |
      Supported by
      [![](resources/rconsortium.png){fig-alt="Posit" width=120px}](https://www.r-consortium.org/)
    center:
      - text: "PharmaRUG 2023"
        href: https://pharmarug.github.io/pharmarug-2023/
      - text: "Open Source Clinical Reporting summeR"
        href: https://insightsengineering.github.io/nest-2023-summeR/
      - text: "PharmaRUG 2024"
        href: https://pharmarug.github.io/pharmarug-2024/

format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 1200px
      margin-width: 200px
      gutter-width: 1.5rem
    theme: cosmo
    mainfont: system-ui
    fontcolor: "#161b58"
    css: styles.css
    toc: false

editor: source
