---
title: "China Pharma R user group meeting 2025"
---

3rd China Pharmaceutical Industry R User Group Meeting will be held on March 28, 2025, both on-site and online. On-site meeting locations: Shanghai (Novartis campus), Beijing (Sanofi campus).

第三届中国医药行业R用户大会将于2024年3月28日召开。线上线下同步进行。线下会议地点：上海（诺华园区），北京（赛诺菲园区）。

Offline registration seats are available for 150 people in Shanghai, 80 people in Beijing, and 100 people online. First come, first served. Online registration ends on March 14th

线下注册席位上海150人，北京80人，线上100人，先到先得。线上注册截至3月14日

Registration for this conference is free, and free coffee breaks will be provided on the day of the conference. Lunch is arranged by yourself, no invoice will be provided for the meeting

此次会议免费注册，会议当天会提供免费茶歇。午餐自行安排，会议不提供发票

Conference registration is now open, please register through the following link

会议注册现已开启，请通过如下链接注册

https://docs.qq.com/form/page/DWXpRdG54aUdvb0ta#/fill-detail



| Key dates                 |                                    |
| ------------------------- | ---------------------------------- |
| 13-Dec-2024               | Call for Papers Opens              |
| 31-Jan-2025               | Call for Papers Closes             |
| 1-Feb-2025 to  7-Feb-2025 | Acceptance Notices Sent to Authors |
| 3-Feb-2025                | Conference Registration Opens      |
| 7-Mar-2025               | Conference Registration Closes     |
| 21-Mar-2025               | Final Papers/Slides Due            |
| 28-Mar-2025               | China Pharma R User Group meeting  |


Conference organising committee: Baoqing Li (Johnson & Johnson), Fan Zhang (Sanofi) and Joe Zhu (Roche)
